# Generated by Django 4.1.3 on 2022-11-02 02:13

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('non_listed', 'No Listed')], max_length=30)),
                ('path', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('uuid', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('cid', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.CharField(blank=True, max_length=220, null=True)),
                ('expiration', models.CharField(choices=[('NEVER', 'Never'), ('10_MINUTES', '10 Minutes'), ('1_HOUR', '1 Hour'), ('1_DAY', '1 Day'), ('1_WEEk', '1 Week'), ('2_WEEk', '2 Weeks'), ('1_MONTH', '1 Month'), ('6_MONTH', '6 Month'), ('1_YEAR', '1 Year')], max_length=30)),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=40), null=True, size=None)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_address', models.CharField(blank=True, default='', max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('manifest_cid', models.CharField(blank=True, max_length=120, null=True)),
                ('manifest_path', models.CharField(blank=True, max_length=120, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.paste')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, default='', max_length=120)),
                ('cid', models.CharField(blank=True, max_length=120, null=True)),
                ('file_name', models.CharField(blank=True, max_length=120, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('syntax', models.CharField(blank=True, max_length=40, null=True)),
                ('paste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.paste')),
            ],
        ),
    ]
